apiVersion: v1
kind: Service
metadata:
  name: k8s-terminal
  namespace: default
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  sessionAffinity: None
  type: NodePort
  selector:
    app: k8s-terminal