apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy
      containers:
        - name: proxy
          image: xxxxxx
          imagePullPolicy: Always
