apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy
  namespace: default
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: proxy
subjects:
  - kind: ServiceAccount
    name: proxy
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

